server:
  port: 8080
spring:
  application:
    name: "Balances"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapter:
  restconsumer:
    url: "https://proyectobanco.getsandbox.com"
